from typing import Any


class ProjectGenerator:
    """Turns an application specification into a minimal project manifest."""

    def generate(self, specification: dict[str, Any]) -> list[dict[str, str]]:
        project = specification["project"]
        return [
            {
                "path": "README.md",
                "content": f"# {project}\n\nGenerated by AI Application Factory.\n",
            },
            {
                "path": "apps/api/main.py",
                "content": "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/health')\ndef health():\n    return {'status': 'ok'}\n",
            },
            {
                "path": "apps/web/README.md",
                "content": "# Web application\n\nNext.js application generated by AI Application Factory.\n",
            },
        ]
