from pathlib import Path
from uuid import uuid4
from zipfile import ZipFile
from app.schemas.generation import GenerateRequest

ROOT = Path(__file__).resolve().parents[4]
TEMPLATE_ROOT = ROOT / "packages" / "templates"
OUTPUT_ROOT = ROOT / "storage" / "generated"

TEMPLATES = {
    "fastapi-api": "A minimal FastAPI service",
    "react-dashboard": "A minimal React dashboard",
}


def list_templates() -> list[dict[str, str]]:
    return [{"id": key, "description": value} for key, value in TEMPLATES.items()]


def generate_project(request: GenerateRequest) -> dict[str, str]:
    if request.template not in TEMPLATES:
        raise ValueError(f"Unsupported template: {request.template}")

    project_id = f"proj_{uuid4().hex[:12]}"
    project_root = OUTPUT_ROOT / project_id
    project_root.mkdir(parents=True, exist_ok=True)

    (project_root / "README.md").write_text(
        f"# {request.name}\n\n{request.description}\n\nGenerated by AI Application Factory.\n",
        encoding="utf-8",
    )
    (project_root / "factory.json").write_text(
        '{\n'
        f'  "project_id": "{project_id}",\n'
        f'  "name": "{request.name}",\n'
        f'  "template": "{request.template}"\n'
        '}\n',
        encoding="utf-8",
    )
    return {"project_id": project_id, "status": "completed", "template": request.template, "path": str(project_root)}


def export_project(project_id: str) -> dict[str, str]:
    project_root = OUTPUT_ROOT / project_id
    if not project_root.is_dir():
        raise ValueError(f"Project not found: {project_id}")
    archive = OUTPUT_ROOT / f"{project_id}.zip"
    with ZipFile(archive, "w") as zip_file:
        for path in project_root.rglob("*"):
            if path.is_file():
                zip_file.write(path, path.relative_to(project_root))
    return {"project_id": project_id, "status": "exported", "archive": str(archive)}
